from langchain_core.tools import tool


@tool
def generate_report(title: str, sections: list[str]) -> str:
    """Generate a formatted markdown report from a title and list of content sections.
    Each section should be a string with the section content."""
    lines = [f"# {title}", ""]
    for i, section in enumerate(sections, 1):
        lines.append(section)
        lines.append("")
    lines.append("---")
    lines.append("*Report generated by Supply Chain Intelligence Agents*")
    return "\n".join(lines)
